# Generated by Django 6.1 on 2026-09-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("writing_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientVoiceBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField()),
                ("model_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_baseline",
                        to="writing_test.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("vowel", "Sustained Vowel"),
                            ("ddk", "Diadochokinetic (pa-ta-ka)"),
                            ("reading", "Reading Passage"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "stability_score",
                    models.FloatField(
                        help_text="Calibrated 0-100 stability score for this test"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        help_text="128-D embedding vector, stored for trend recomputation"
                    ),
                ),
                (
                    "raw_features",
                    models.JSONField(
                        blank=True,
                        help_text="Interpretable acoustic features: jitter, shimmer, HNR, F0, etc.",
                        null=True,
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("audio_duration_sec", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_test_results",
                        to="writing_test.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "task_type", "created_at"],
                        name="voice_test__patient_e765dd_idx",
                    )
                ],
            },
        ),
    ]
